aws_dbt_snowflake:
  outputs:
    dev:
      account: AUAFMVM-KR36862
      database: AIRBNB
      password: Kaushik@9381491409
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: KAUSHIKKOHLI18
      warehouse: COMPUTE_WH
  target: dev

